# Generated by Django 4.2.26 on 2025-11-14 18:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["unit", "name"],
            },
        ),
        migrations.CreateModel(
            name="MCQTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "passing_score",
                    models.IntegerField(
                        default=70,
                        help_text="Passing percentage",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "time_limit_minutes",
                    models.IntegerField(
                        default=30,
                        help_text="Time limit in minutes",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["video"],
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("operation_code", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "is_ctq_station",
                    models.BooleanField(
                        default=False, help_text="Critical to Quality station"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="process_dojo.line",
                    ),
                ),
            ],
            options={
                "ordering": ["line", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("option_a", models.CharField(max_length=500)),
                ("option_b", models.CharField(max_length=500)),
                ("option_c", models.CharField(max_length=500)),
                ("option_d", models.CharField(max_length=500)),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[
                            ("A", "Option A"),
                            ("B", "Option B"),
                            ("C", "Option C"),
                            ("D", "Option D"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "marks",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "ordering",
                    models.IntegerField(default=0, help_text="Question order in test"),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Explanation for correct answer"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="process_dojo.mcqtest",
                    ),
                ),
            ],
            options={
                "ordering": ["test", "ordering", "id"],
            },
        ),
        migrations.CreateModel(
            name="TrainingVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("video_file", models.FileField(upload_to="training_videos/%Y/%m/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="video_thumbnails/"
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        default=0, help_text="Video duration in seconds"
                    ),
                ),
                ("has_voice", models.BooleanField(default=True)),
                ("has_callouts", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="process_dojo.operation",
                    ),
                ),
            ],
            options={
                "ordering": ["operation", "order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TestAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("correct_answers", models.IntegerField(default=0)),
                ("total_questions", models.IntegerField(default=0)),
                ("passed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_saved_at", models.DateTimeField(auto_now=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="process_dojo.mcqtest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_option",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Option A"),
                            ("B", "Option B"),
                            ("C", "Option C"),
                            ("D", "Option D"),
                        ],
                        max_length=1,
                    ),
                ),
                ("is_correct", models.BooleanField(default=False)),
                ("saved_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_answers",
                        to="process_dojo.testattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_answers",
                        to="process_dojo.question",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mcqtest",
            name="video",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mcq_test",
                to="process_dojo.trainingvideo",
            ),
        ),
        migrations.CreateModel(
            name="LoginSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
                ("session_duration_minutes", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-login_time"],
            },
        ),
        migrations.AddField(
            model_name="line",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="process_dojo.unit",
            ),
        ),
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("plant", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                (
                    "biometric_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["employee_id"],
            },
        ),
        migrations.CreateModel(
            name="VideoCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completion_percentage",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("access_count", models.IntegerField(default=0)),
                ("last_watched_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_completions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="process_dojo.trainingvideo",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_watched_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_completed"],
                        name="process_doj_user_id_ef162f_idx",
                    ),
                    models.Index(
                        fields=["video", "is_completed"],
                        name="process_doj_video_i_7f22be_idx",
                    ),
                    models.Index(
                        fields=["-last_watched_at"],
                        name="process_doj_last_wa_bccd0f_idx",
                    ),
                ],
                "unique_together": {("user", "video")},
            },
        ),
        migrations.AddIndex(
            model_name="trainingvideo",
            index=models.Index(
                fields=["operation", "is_active"], name="process_doj_operati_fe8a55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testattempt",
            index=models.Index(
                fields=["user", "status"], name="process_doj_user_id_50e86e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testattempt",
            index=models.Index(
                fields=["test", "status"], name="process_doj_test_id_5ac201_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testattempt",
            index=models.Index(
                fields=["-started_at"], name="process_doj_started_bc8c16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedanswer",
            index=models.Index(
                fields=["attempt", "question"], name="process_doj_attempt_0ae5ed_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedanswer",
            unique_together={("attempt", "question")},
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["test", "ordering"], name="process_doj_test_id_2868f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(
                fields=["line", "is_active"], name="process_doj_line_id_627adb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(
                fields=["is_ctq_station"], name="process_doj_is_ctq__43bd39_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="operation",
            unique_together={("line", "name")},
        ),
        migrations.AddIndex(
            model_name="loginsession",
            index=models.Index(
                fields=["user", "-login_time"], name="process_doj_user_id_9db293_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginsession",
            index=models.Index(
                fields=["-login_time"], name="process_doj_login_t_d1e908_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="line",
            index=models.Index(
                fields=["unit", "is_active"], name="process_doj_unit_id_531096_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="line",
            unique_together={("unit", "name")},
        ),
        migrations.AddIndex(
            model_name="employeeprofile",
            index=models.Index(
                fields=["employee_id"], name="process_doj_employe_2a5622_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeeprofile",
            index=models.Index(
                fields=["plant", "unit"], name="process_doj_plant_e905dd_idx"
            ),
        ),
    ]
